### ISSUE TITLE
Server Crash.

### ISSUE THREAD

**Issue by StoneLegion** [Trinsdar/Nano-Chisel#1]
Hey First bug report :) I said I was going try this in my pack!

https://pastebin.com/CfZKz3rG

So it seems to crash on server start look like client side features being activated on the server.

**Comment by CritFlaw** [comment]
Same crash over here.

**Comment by TimGoll** [comment]
Came here to report this but you two were faster

**Comment by Trinsdar** [comment]
is that the beta vanilla fix with the ram and loading time saving features? if so can you remove it and see if it happens still?

**Comment by CritFlaw** [comment]
I don't have vanillafix in my pack.

**Comment by Trinsdar** [comment]
ok that rules that out

**Comment by Trinsdar** [comment]
@KaneHart could you try this version? https://github.com/Trinsdar/Power-Chisels/releases/tag/1.0.0-beta-2-pre

**Comment by TimGoll** [comment]
@Trinsdar I Tried your new version and it still crashes: https://gist.github.com/TimGoll/59a2150b9e44ff75a5632a60b7d53ab0

Looks to me like a client/server error. The tooltip function is client only and is called on the server.

**Comment by Trinsdar** [comment]
ok I think I fixed it this time for real. I tested with the dev server and it didn't crash. still would like you to make sure since bugs can sometimes popup outside the dev enviorment: https://github.com/Trinsdar/Power-Chisels/releases/tag/1.0.0-beta-2-pre2

**Comment by TimGoll** [comment]
I'm not at home over the weekend. But I can test it on sunday

**Comment by CritFlaw** [comment]
I'll give it a go later today.

**Comment by TimGoll** [comment]
Can confirm, your newest beta does work indeed! Thanks! Looking forward to a fast release

**Comment by CritFlaw** [comment]
Woops, forgot to test it. Sorry about that.

**Comment by Trinsdar** [comment]
closing this now as it's released
