### ISSUE TITLE
Connecting to a Server without Power Chisels Error.

### ISSUE THREAD

**Issue by StoneLegion** [Trinsdar/Nano-Chisel#2]
So I decided to remove temp power chisel from the server and sadly now this error comes up:
https://pastebin.com/ztndwNz5

I feel like super light weight mod like this should not act up while connecting to a server even if the server does not have the mod.

**Comment by Trinsdar** [comment]
seems like it's an issue with ic2 advanced crafting. I might just convert to json crafting recipe files

**Comment by Trinsdar** [comment]
after some pondering i think it's on ic2's end, though I could be wrong

**Comment by Trinsdar** [comment]
@KaneHart would you be able to post an issue on ic2's bug tracker and link back here?
https://bt.industrial-craft.net/my_view_page.php

**Comment by StoneLegion** [comment]
Sorry what would I be posting? As so many outside mods support IC2 just fine? I mean I can but what am I actually asking for?

**Comment by Trinsdar** [comment]
Just post an issue linking back here saying that when my mod is removed it crashes, as I think it's on their side, although there still is the possibility that I fucked up something.

**Comment by Trinsdar** [comment]
@KaneHart could you post the debug log

**Comment by Trinsdar** [comment]
so I can't seem to reproduce it

**Comment by Trinsdar** [comment]
I'm going to close this as it seems there is no issue anymore. If I get more proof that it still exist then I will reopen it.
