### ISSUE TITLE
Icon rendering is wrong

### ISSUE THREAD

**Issue by TimGoll** [Trinsdar/Nano-Chisel#3]
Your newest beta (v2) has a model error:
![image](https://user-images.githubusercontent.com/13639408/51528145-4cf98900-1e36-11e9-9c79-0025688431cd.png)

**Comment by Trinsdar** [comment]
I'm going to have to test later, but can you reproduce it without shaders? They are known to cause some problems with mods.

**Comment by TimGoll** [comment]
I could, yes. But this looks like a mistake in the json files

**Comment by TimGoll** [comment]
![image](https://user-images.githubusercontent.com/13639408/51542195-f3f01c00-1e5a-11e9-8304-4397fca7e09e.png)
without shaders
